### ISSUE TITLE
Powershell strange behavior, critical but not alerting

### ISSUE THREAD

**Issue by jothoma1** [sensu-plugins/sensu-plugins-windows#38] opened 2017-03-23 13:54 UTC
Hi,
I'm having a strange issue on a Windows 2008 R2 server. I'm using the powershell checks and the disk checks reports critical (and it is true) but in uchiwa it appears as OK.
![checkspowershell](https://cloud.githubusercontent.com/assets/19167503/24250860/9518f4e6-0fd8-11e7-91dc-47d444d700e2.png)

Do you have any idea why ?

**Comment by eheydrick** [comment] 2017-03-24 06:54
@simonsteur any ideas?

**Comment by simonsteur** [comment] 2017-03-24 07:34
Interesting, will see if I can reproduce this.

**Comment by simonsteur** [comment] 2017-03-24 08:04
@jothoma1 which version of powershell is running on the server?

**Comment by simonsteur** [comment] 2017-03-24 08:29
I think I located the issue:

powershell 2.0 doesn't return any other exit code than 0 or 1 properly when running a command with the`-file` parameter. When running the script itself it will return the currect exit code. You can test this by doing the following:

on a 2008 r2 machine with powershell version 2.0 execute the check disk script from a powershell prompt and then check the $lastexitcode. You will see the correct exit code (2). 

now call on the same script but instead use the` -file` parameter like so:
`powershell.exe -file .\check-windows-disk.ps1 5 10` , again check the $lastexitcode. You will now receive the exit code 0.

This can be resolved by replacing `exit 2` with `[System.Environment]::Exit(2)` but this creates a dependency on the .net framework. which means that default installations of server 2012 (r2) core will not support these checks out of the box since the .net framework is not installed by default.

I personally don't think that such a dependency should be put in place but rather that we require atleast powershell version 3.0 and encourage people to upgrade the powershell version on their machines. 

@eheydrick your thoughts on this?

**Comment by jothoma1** [comment] 2017-03-25 08:19
@simonsteur i'm using powershell 2.0 on a french 2008 R2

**Comment by simonsteur** [comment] 2017-03-30 06:25
@jothoma1 I highly recommend upgrading to a newer version of powershell (requires a reboot) https://www.microsoft.com/en-us/download/details.aspx?id=50395 or making the changes that I listed in the comment above.

**Comment by majormoses** [comment] 2017-07-04 04:52
Is there anything else to do here? unless someone wants to donate time to invest in making powershell 2 work I think we should close this as we now document the min powershell version supported.

**Comment by simonsteur** [comment] 2017-07-05 15:01
I don't think that any work to make PS v2 work is worth it and we should just close this one.

**Comment by majormoses** [comment] 2017-07-05 15:28
@simonsteur agreed on the powershell v2 thing. I was just checking if it was worth putting something in the readme to describe this behavior and thus prevent this being asked again. I will close this out and if someone wants to submit a documentation PR I am more than review and merge it.

**Closed by majormoses** 2017-07-05 15:28 UTC
