### ISSUE TITLE
Checks do not show an output.

### ISSUE THREAD

**Issue by AirCombat** [sensu-plugins/sensu-plugins-windows#18] opened 2016-04-21 19:24 UTC
Checks do not show an output and my test for the service TermService wont fail when I stop the service.

```
{
  "timestamp": "2016-04-21T20:13:37.279548+0100",
  "level": "info",
  "message": "publishing check result",
  "payload": {
    "client": "servername",
    "check": {
      "command": "metrics-windows-uptime.rb",
      "standalone": true,
      "interval": 60,
      "name": "Uptime",
      "issued": 1461266017,
      "executed": 1461266017,
      "duration": 0.054,
      "output": "",
      "status": 0
    }
  }
}
```

Less is sometimes more, but not in this case.

Windows 10, Sensu .23, Gem version 0.0.10

```

{
    "checks": {
        "Disk": {
            "command": "check-windows-disk.rb -w 85 -c 95",
            "standalone": true,
            "interval": 120
        },
        "CPU": {
            "command": "check-windows-cpu-load.rb -w 85 -c 95",
            "standalone": true,
            "interval": 60
        },
        "RAM": {
            "command": "check-windows-ram.rb -w 85 -c 95",
            "standalone": true,
            "interval": 60
        },
        "Uptime": {
            "command": "metrics-windows-uptime.rb",
            "standalone": true,
            "interval": 60
        },
        "RDP_Service": {
            "command": "check-windows-service.rb -s TermService",
            "standalone": true,
            "interval": 60
        }
    }
}
```

**Comment by julianrubisch** [comment] 2016-10-29 16:02
+1, have you found out why, or where to debug?

**Comment by jeremysmitherman** [comment] 2016-11-11 18:44
It seems to me some of checks that call popen sometimes hang forever, and that might be causing some of these issues.

**Comment by vardyb** [comment] 2017-03-10 10:42
+1 
I'm also finding that none of the windows checks are sending an output, this is the same for both types , checks and metrics.  If the plugin is run from the command line then the check/metric does output, but  is empty once the check/metric reaches the Sensu Server.

`
C:\opt\sensu\embedded\mingw>ruby C:\opt\sensu\etc\plugins\metric-windows-disk-usage.rb
REMOVED.disk_usage.disk_C.used 20975.95 1489138686
REMOVED.disk_usage.disk_C.avail 40462.05 1489138686
REMOVED.disk_usage.disk_C.used_percentage 34 1489138686
`
And the output received at the Sensu Server:

`
{
  "client": {
    "name": "REMOVED",
    "address": "REMOVED",
    "subscriptions": [
      "client:REMOVED"
    ],
    "version": "0.28.2",
    "timestamp": 1489141103
  },
  "check": {
    "command": "C:\\opt\\sensu\\etc\\plugins\\metric-windows-disk-usage.rb",
    "interval": 600,
    "standalone": true,
    "type": "metric",
    "handler": "win-metrics",
    "name": "disk_usage",
    "issued": 1489141117,
    "executed": 1489141117,
    "duration": 0.062,
    "output": "",
    "status": 0,
    "history": [
      "0",
      "0"
    ],
    "total_state_change": 0
  },
  "occurrences": 1,
  "occurrences_watermark": 1,
  "action": "create",
  "timestamp": 1489141118,
  "id": "REMOVED",
  "last_ok": 1489141118,
  "silenced": false,
  "silenced_by": [
  ]
}
`
Output is also showing empty in the sensu-client.log.

This is the same behaviour across all the checks and metrics.  I am running the checks on a Windows Server 2012. Sensu Server is running on RHEL 6.8.

Any help is resolving this would be much appreciated.

**Comment by JohnPayment** [comment] 2017-03-20 18:32
I have had exactly the same issue on Windows Server 2008. The output is fine on the command line but blank when received by the sensu server.

`C:/opt/sensu/embedded/bin/ruby.exe C:/opt/sensu/embedded/bin/check-windows-disk.rb -c 90% -w 80%`

However, in the course of trying to find a way to fix this it just started working. It seems that after resetting the server several times, it eventually decided to work with a command that previously produced a blank result. While I'm happy that this particular VM is being properly monitored, I haven't much confidence in my ability to reliably reproduce this functionality on other VMs.

**Comment by vardyb** [comment] 2017-03-21 08:16
@JohnPayment  I've managed to get this working on our environment. The problem was that I was not including the ruby interpreter in the check's 'command' configuration.  Since adding this I am now getting output sent to the sensu server.  Here is an example.

```javascript
{
  "checks": {
    "cpu_percent": {
      "command": "c:\\opt\\sensu\\embedded\\bin\\ruby C:\\opt\\sensu\\etc\\plugins\\metric-windows-cpu-load.rb",
      "interval": 30,
      "type": "metric",
      "handler": "win_metrics",
      "subscribers": ["win_metrics"]
    }
}`

**Comment by majormoses** [comment] 2017-06-03 06:30
@vardyb can you put together a pr with this in the readme?

**Comment by vardyb** [comment] 2017-06-03 13:31
@majormoses yes will do.  Probably be tomorrow.

**Closed** 2019-07-21 08:55 UTC
Labels: Help Wanted, Status: Feedback Requested, Type: Documentation
