### ISSUE TITLE
powershell.exe Terminated

### ISSUE THREAD

**Issue by stevebanik-ndsc** [sensu-plugins/sensu-plugins-windows#42] opened 2017-05-12 14:16 UTC
Resource Monitor is showing Terminated powershell.exe processes each time Sensu runs the check.  Is there a way to close powershell.exe more gracefully?  I'm also curious if CPU usage can be decreased with these checks, as they tend to spike each time powershell.exe is invoked.

**Comment by majormoses** [comment] 2017-06-03 06:22
might be related? https://github.com/sensu-plugins/sensu-plugins-windows/pull/39 can you validate if you are using poweshell 2?

**Comment by simonsteur** [comment] 2017-06-20 09:59
Also regarding the cpu spikes. how does your command look to initiate the powershell check? It's best to start powershell with the following flags to reduce the cpu usage: `Powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo`

**Comment by stevebanik-ndsc** [comment] 2017-06-20 14:05
@majormoses PSVersion = 4.0

**Comment by stevebanik-ndsc** [comment] 2017-06-20 14:07
@simonsteur I've included `Powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo` in the .json file.

**Comment by simonsteur** [comment] 2017-06-22 13:47
@stevebanik-ndsc Sorry for my confusion but do you mean you already had that included or that you added it now. Incase of the second, do you see any difference? 

Also to pick up on that powershell is listed as terminated in resource monitor. That is expected behavior and has nothing to do with a graceful exit of an application. The resource monitor shows terminated processes for a short while, their cpu usage, etc. This is the case for all applications, regardless of how they exit. 

Since your sensu checks will run every x amount of time, powershell.exe will probably have a permanent place among the terminated processes.  This is nothing to be concerned about and completely normal.

**Comment by majormoses** [comment] 2017-07-02 22:37
It sounds like this is intended behavior, is there anything to actually be done here? Maybe something in the readme would help?

**Comment by stevebanik-ndsc** [comment] 2017-07-05 14:32
@simonsteur I already had that included.  What you've described regarding "terminated" in Resource Monitor makes sense.  Thanks for that info.

**Comment by majormoses** [comment] 2017-09-26 00:06
closing this out then, please feel free to message back if you feel this should remain open.

**Closed by majormoses** 2017-09-26 00:06 UTC
Labels: Feedback Requested
